version: "3.9"

volumes:
    logs:
        driver: local

networks:
    lumen-app:

services:
    app:
        container_name: simple-api-app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_DEBUG=${APP_DEBUG:-true}
            - APP_KEY=${APP_KEY:-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
            - APP_ENV=${APP_ENV:-local}
            - APP_URL=${APP_URL:-http://localhost}
            - APP_PORT=${APP_PORT:-8080}
            - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
            - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
            - DB_CONNECTION=${DB_CONNECTION:-mysql}
            - DB_HOST=${DB_HOST:-mysql}
            - DB_PORT=${DB_PORT:-3306}
            - DB_DATABASE=${DB_DATABASE:-lumendb}
            - DB_USERNAME=${DB_USERNAME:-lumen}
            - DB_PASSWORD=${DB_PASSWORD:-secret}
        ports:
            - 8080:${APP_PORT}
        volumes:
            - .:/var/www/html
            - ./storage/logs:/var/www/logs
        depends_on:
            - db
        networks:
            - lumen-app

    redis:
        container_name: simple-api-redis
        image: redis:latest
        volumes:
            - ./docker/redis:/data
        ports:
            - 6381:6379
        environment:
            - TZ=${APP_TIMEZONE}
        networks:
            - lumen-app

    db:
        container_name: simple-api-db
        image: mysql:8.0
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-lumendb}
            - MYSQL_USER=${DB_USERNAME:-lumen}
            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
        ports:
            - 3307:3306
        networks:
            - lumen-app

    pma:
        container_name: simple-api-pma
        image: phpmyadmin:latest
        depends_on:
            - db
        environment:
            PMA_HOST: db
        ports:
            - 8002:80
        networks:
            - lumen-app

    rabbitmq:
        container_name: simple-api-rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - 5673:5672
            - 15673:15672
        environment:
            - TZ="${APP_TIMEZONE}"
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        volumes:
            - ./docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
            - ./docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - lumen-app
